parameters:
    knp_bundles.updater.class:    Knp\Bundle\KnpBundlesBundle\Updater\Updater
    knp_bundles.user.provider:    Knp\Bundle\KnpBundlesBundle\Security\Core\User\KnpbundlesUserProvider

services:
    knp_bundles.updater:
        class:                    %knp_bundles.updater.class%
        arguments:                [@knp_bundles.entity_manager, %knp_bundles.git_bin%, %knp_bundles.repos_dir%]
    knp_bundles.user.provider:
        class:                    %knp_bundles.user.provider%
        arguments:                [@knp_bundles.entity_manager]